### ISSUE TITLE
默认播放列表自动爬取最热音乐 

### ISSUE THREAD

**Issue by JumpAlang** [hanhuoer/Musicoo#3]

**Comment by hanhuoer** [comment]
已添加该功能。[#dfa9167dee4cc2922ddc20bfa7fee19afd94c31b](https://github.com/hanhuoer/Musicoo/commit/dfa9167dee4cc2922ddc20bfa7fee19afd94c31b)

可以获取指定歌单的数据，注释中 3778678 为热歌榜。
